### ISSUE TITLE
[Suggestion] GraalVM Java and its arguments.

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/Tankoptimization#1]
详见：https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks

**Comment by Kasualix** [comment]
可以简单说一说吗
不是很懂jvm参数qwq

**Comment by wasdspace** [comment]
我也不是很懂QAQ，而且原文太长了，效果也因人而异，所以不如就把上面的链接贴在这，最多再放几个下载直链：
- Windows AMD64 (64-bit)：https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_1/graalvm-ee-java11-windows-amd64-22.3.1.zip

- Linux AMD64 (64-bit): https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_1/graalvm-ee-java11-linux-amd64-22.3.1.tar.gz

- Linux AARCH64 (ARM 64-bit): https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_1/graalvm-ee-java11-linux-aarch64-22.3.1.tar.gz

- Mac AMD64 (64-bit): https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_1/graalvm-ee-java11-darwin-amd64-22.3.1.tar.gz

然后放个原文中关于GraalVM的基本参数：

`-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise`

PS：如果决意要用Memory Sweep的话，应该要把`-XX:+DisableExplicitGC`替换成`-XX:+ExplicitGCInvokesConcurrent`，
也就是：

`-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise`

不过在1.12.2中显性调用System.gc()似乎只适用于类似贪婪整合包的极端情况：https://www.curseforge.com/minecraft/mc-mods/memory-cleaner-mod?comment=15 ，不知道1.16.5如何

GraalVM只能使用G1GC，而使用原文中的G1GC优化参数在我设备上的表现反而更差，大概是作者列出的参数很激进、在追求极限值吧……

GraalVM能大大减少启动时间（在我的测试中，300+模组，启动时间少了一分多钟，艹，好像重要的就这一个），区块加载速度据原文所述可以提升20%。而且原文作者也比较活跃，我觉得你可以关注一下

与GraalVM无关：

- 原文中还说，要让分配给Minecraft的最小内存=最大内存，说是有[好处](https://dzone.com/articles/benefits-of-setting-initial-and-maximum-memory-siz)但我没感觉出来。并且国内启动器很少有这个功能（一般只允许设定最大内存），所以又要玩家手动添加JVM参数

- 关于进程优先级，最好将其设置为**较高**而不能为**高**（很可惜PCL2没有“较高”这个选项），不然可能会适得其反：https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks/issues/15

**Comment by Kasualix** [comment]
放弃思考，我直接把这个 Issue 贴上去好了
![image](https://user-images.githubusercontent.com/110756250/218102361-821dfda4-3596-42e2-b654-7fdfc00fef98.png)

![T3~(CUZXM DOUG8RN}3XPVF](https://user-images.githubusercontent.com/110756250/218102321-73197c4c-f718-4ed6-915f-7d786b392eed.gif)
