### ISSUE TITLE
RoadRunner 可以换成 Does It Tick? 吗

### ISSUE THREAD

**Issue by SulfuricM** [MCTeamPotato/Tankoptimization#3]
RoadRunner 没法用 OpenJ9 17启动

**Comment by Kasualix** [comment]
短时间内应该不会，你可以自己换。

第一个原因：在我看来，1165 用 Java 17 启动本身就是过于激进了，不如 Java 16。

第二个原因：有计划接盘 DIT 和 RoadRunner，把两者冲突的 mixin 删一删融一融让它们能共用。

**Comment by SulfuricM** [comment]
啊不，没法启动的主要原因是OpenJ9 17，换OpenJDK 17就行了，没试过其他版本的OpenJ9

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/DoesPotatoTick
换这个吧
